name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: build release 
      run: ./gradlew assembleRelease
      
    - name: list files
      run: ls -lrt app/build/outputs/apk/release
        
    - name: Firebase App Distribution Action
      # You may pin to the exact commit or the version.
      # uses: hasretsariyer/firebase-app-distribution-github-action@1efdc61b2aecd54be4072edb5dd527be26571943
      uses: hasretsariyer/firebase-app-distribution-github-action@v1.0
      with:
        # Firebase App ID. You can find it in the Firebase console, on the General Settings page.
        app_id: ${{secrets.FIREBASE_APP_ID}}
        app_file: app/build/outputs/apk/release/app-release.apk

        firebase_token: ${{secrets.FIREBASE_TOKEN}}
        tester_groups: testers
